const SET_FRIENDS = "SET_FRIENDS";
const SET_USERS = "SET_USERS";
const RESET_USERS = "RESET_USERS";
const SET_MESSAGES = "SET_MESSAGES";
const ADD_NEW_MESSAGE = "ADD_NEW_MESSAGE";
const RESET_FRIENDS = "RESET_FRIENDS";
const SET_USER_DATA = "SET_USER_DATA";
const RESET_USER_DATA = "RESET_USER_DATA";
const SET_SELECTED_USER = "SET_SELECTED_USER";
const RESET_STATE = "RESET_STATE";
const RESET_PAGINATION = "RESET_PAGINATION";
const SET_PAGE = "SET_PAGE";
const ADD_FRIEND = "ADD_FRIEND";
const SET_NAVIGATION = "SET_NAVIGATION";
const ADD_OR_MOVE_FRIEND_TO_FRONT = "ADD_OR_MOVE_FRIEND_TO_FRONT";

export default {
    SET_FRIENDS,
    SET_USERS,
    RESET_USERS,
    SET_MESSAGES,
    ADD_NEW_MESSAGE,
    RESET_FRIENDS,
    SET_USER_DATA,
    RESET_USER_DATA,
    SET_SELECTED_USER,
    RESET_STATE,
    RESET_PAGINATION,
    SET_PAGE,
    ADD_FRIEND,
    SET_NAVIGATION,
    ADD_OR_MOVE_FRIEND_TO_FRONT
}